### ISSUE TITLE
NameError: uninitialized constant Igdb::Configuration

### ISSUE THREAD

**Issue by rbraaf** [ahmetabdi/igdb#2]
I keep getting this error (`NameError: uninitialized constant Igdb::Configuration`) anytime I try to use the `Igdb.connect` method in IRB.

I can provide any additional information if needed.
Ruby version: 2.2.3

**Comment by ahmetabdi** [comment]
Fixed in version `0.7.0`.

`$ require 'igdb'`
`$ Igdb.connect('api_key')`

**Comment by rbraaf** [comment]
Thanks for the update!
